### PR TITLE
Don't hold both locks when processing event data

### LINKED ISSUE #921: rmw_zenoh_cpp: deadlock
### Generated by Generative AI

_No response_

### Operating System:

Ubuntu 22.04

### ROS version or commit hash:

jazzy

### RMW implementation (if applicable):

rmw_zenoh

### RMW Configuration (if applicable):

Hi,

We have been able to trigger this deadlock repeatedly when using `ros2 bag record` on topics transporting relatively large data (multiple video streams), usually within a few minutes.
From the recording side, no error is reported, but the recorded bag file just stops growing.

Please find below the relevant  backtraces showing which threads and parts of the code deadlock.
Based on these data, we could come up with a patch to resolve the issue, but I did not submit it since it feels more like a workaround and not the way to go for something to merge.

Let us know if you need more information.

```
Thread 13 (Thread 0xffff5a22f120 (LWP 39482) "ros2"):
#0  0x0000ffff89949ffc in ?? () from /lib/aarch64-linux-gnu/libc.so.6
#1  0x0000ffff8995070c in pthread_mutex_lock () from /lib/aarch64-linux-gnu/libc.so.6
#2  0x0000ffff871e77b4 in __gthread_mutex_lock (__mutex=0xaaaaed12aa30) at /usr/include/aarch64-linux-gnu/c++/11/bits/gthr-default.h:749
#3  0x0000ffff871e7814 in std::mutex::lock (this=0xaaaaed12aa30) at /usr/include/c++/11/bits/std_mutex.h:100
#4  0x0000ffff871e7908 in std::lock_guard<std::mutex>::lock_guard (this=0xffff5a22d260, __m=...) at /usr/include/c++/11/bits/std_mutex.h:229
#5  0x0000ffff8725b29c in rmw_zenoh_cpp::SubscriptionData::queue_has_data_and_attach_condition_if_not (this=0xaaaaed12aa20, wait_set_data=0xaaaaed03eef0) at /home/sevensense/ws/src/rmw_zenoh/src/detail/rmw_subscription_data.cpp:359
#6  0x0000ffff8727b394 in (anonymous namespace)::check_and_attach_condition (subscriptions=0xaaaaed09d708, guard_conditions=0xaaaaed09d720, services=0xaaaaed09d750, clients=0xaaaaed09d738, events=0xaaaaed09d768, wait_set_data=0xaaaaed03eef0) at /home/sevensense/ws/src/rmw_zenoh/src/rmw_zenoh.cpp:2138
#7  0x0000ffff8727b788 in rmw_wait (subscriptions=0xaaaaed09d708, guard_conditions=0xaaaaed09d720, services=0xaaaaed09d750, clients=0xaaaaed09d738, events=0xaaaaed09d768, wait_set=0xaaaaed031920, wait_timeout=0x0) at /home/sevensense/ws/src/rmw_zenoh/src/rmw_zenoh.cpp:2223
#8  0x0000ffff88abcb24 in rcl_wait () from /opt/ros/current/lib/librcl.so
#9  0x0000ffff85ec6130 in ?? () from /opt/ros/current/lib/librclcpp.so
#10 0x0000ffff85ec3aa8 in rclcpp::Executor::wait_for_work(std::chrono::duration<long, std::ratio<1l, 1000000000l> >) () from /opt/ros/current/lib/librclcpp.so
#11 0x0000ffff85ec5fec in rclcpp::Executor::get_next_executable(rclcpp::AnyExecutable&, std::chrono::duration<long, std::ratio<1l, 1000000000l> >) () from /opt/ros/current/lib/librclcpp.so
#12 0x0000ffff85ede5c8 in rclcpp::executors::SingleThreadedExecutor::spin() () from /opt/ros/current/lib/librclcpp.so
#13 0x0000ffff888431fc in ?? () from /lib/aarch64-linux-gnu/libstdc++.so.6
#14 0x0000ffff8994d5c8 in ?? () from /lib/aarch64-linux-gnu/libc.so.6
#15 0x0000ffff899b5edc in ?? () from /lib/aarch64-linux-gnu/libc.so.6

Thread 8 (Thread 0xffff84a5f120 (LWP 39440) "rx-0"):
#0  0x0000ffff89949ffc in ?? () from /lib/aarch64-linux-gnu/libc.so.6
#1  0x0000ffff8995070c in pthread_mutex_lock () from /lib/aarch64-linux-gnu/libc.so.6
#2  0x0000ffff871e77b4 in __gthread_mutex_lock (__mutex=0xaaaaed03ef20) at /usr/include/aarch64-linux-gnu/c++/11/bits/gthr-default.h:749
#3  0x0000ffff871e7814 in std::mutex::lock (this=0xaaaaed03ef20) at /usr/include/c++/11/bits/std_mutex.h:100
#4  0x0000ffff871e7908 in std::lock_guard<std::mutex>::lock_guard (this=0xffff84a5b0d0, __m=...) at /usr/include/c++/11/bits/std_mutex.h:229
#5  0x0000ffff871e747c in rmw_zenoh_cpp::EventsManager::notify_event (this=0xaaaaed12c4d0, event_id=rmw_zenoh_cpp::ZENOH_EVENT_MESSAGE_LOST) at /home/sevensense/ws/src/rmw_zenoh/src/detail/event.cpp:254
#6  0x0000ffff871e70c4 in rmw_zenoh_cpp::EventsManager::update_event_status (this=0xaaaaed12c4d0, event_id=rmw_zenoh_cpp::ZENOH_EVENT_MESSAGE_LOST, current_count_change=1) at /home/sevensense/ws/src/rmw_zenoh/src/detail/event.cpp:196
#7  0x0000ffff8725bbc4 in rmw_zenoh_cpp::SubscriptionData::add_new_message (this=0xaaaaed12aa20, msg=std::unique_ptr<rmw_zenoh_cpp::SubscriptionData::Message> = {...}, topic_name="0/alphasense_driver_ros/cam11/sensor_msgs::msg::dds_::Image_/RIHS01_d31d41a9a4c4bc8eae9be757b0beed306564f7526c88ea6a4588fb9582527d47") at /home/sevensense/ws/src/rmw_zenoh/src/detail/rmw_subscription_data.cpp:535
#8  0x0000ffff8725a544 in operator() (__closure=0xaaaaed12b278, sample=...) at /home/sevensense/ws/src/rmw_zenoh/src/detail/rmw_subscription_data.cpp:228
#9  0x0000ffff8725c2fc in zenoh::detail::closures::Closure<rmw_zenoh_cpp::SubscriptionData::init()::<lambda(const zenoh::Sample&)>, void (*)(), void, const zenoh::Sample&>::call(const zenoh::Sample &) (this=0xaaaaed12b270, args#0=...) at /opt/ros/jazzy/opt/zenoh_cpp_vendor/include/zenoh/detail/closures.hxx:72
#10 0x0000ffff8722e2cc in zenoh::detail::closures::IClosure<void, zenoh::Sample&>::call_from_context (context=0xaaaaed12b270, args#0=...) at /opt/ros/jazzy/opt/zenoh_cpp_vendor/include/zenoh/detail/closures.hxx:42
#11 0x0000ffff8722b824 in zenoh::detail::closures::_zenoh_on_sample_call (sample=0xffff84a5bc40, context=0xaaaaed12b270) at /opt/ros/jazzy/opt/zenoh_cpp_vendor/include/zenoh/detail/closures_concrete.hxx:35
#12 0x0000ffff866dea58 in ?? () from /opt/ros/current/opt/zenoh_cpp_vendor/lib/libzenohc.so
...
```

### Client library (if applicable):

_No response_

### 'ros2 doctor --report' output

_No response_

### Steps to reproduce issue

1. Use `ros2 bag record` to record some image topics.
2. Monitor if the bag file is growing
3. Usually, after a few minutes, the recording hangs

### Expected behavior

The recording does not deadlock and continues to record the data.

### Actual behavior

The recording hangs

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by haudren-woven**
## Description

Fixes #921. A deadlock can happen due to two code paths acquiring both locks in opposite order. The simplest fix is to take the locks in sequence, but not at the same time.

### Did you use Generative AI?

Github Copilot GPT-4.1 was used for some completions.

### Additional Information

I am not sure that this the best way to address the issue, but I'm hoping to get the conversation started.

### CODE REVIEW

File: rmw_zenoh_cpp/src/detail/event.cpp [hunk 1]
```diff
@@ -249,11 +249,16 @@ void EventsManager::notify_event(rmw_zenoh_event_type_t event_id)
     return;
   }
 
-  std::lock_guard<std::mutex> lock(event_condition_mutex_);
-  if (wait_set_data_[event_id] != nullptr) {
-    std::lock_guard<std::mutex> wait_set_lock(wait_set_data_[event_id]->condition_mutex);
-    wait_set_data_[event_id]->triggered = true;
-    wait_set_data_[event_id]->condition_variable.notify_one();
+  // Make sure to not lock both event_mutex_ and event_condition_mutex_ at the same time to avoid deadlocks. We can
```
Comment (Yadunund) [inline rmw_zenoh_cpp/src/detail/event.cpp]: Incomplete comment?

**Review by Yadunund — CHANGES_REQUESTED** [review]

File: rmw_zenoh_cpp/src/detail/event.cpp (hunk 1 above)
Comment (haudren-woven) [reply rmw_zenoh_cpp/src/detail/event.cpp]: Fixed, sorry about that :bow:

**Review by Yadunund — APPROVED** [review]
LGTM and we can backport this fix.

**Comment by haudren-woven** [comment]
@Yadunund : Thank you for approving! I fixed the style issues, could you maybe re-run the CI pipelines?

**Comment by JEnoch** [comment]
Pulls: ros2/rmw_zenoh#937
Gist: https://gist.githubusercontent.com/JEnoch/acfe93bd7a774ce425c0b7e979739f5b/raw/2370db6cb22fa4292c01a046e9fcbdb98c94d691/ros2.repos
BUILD args: "--continue-on-error" --packages-above-and-dependencies zenoh_cpp_vendor zenoh_security_tools rmw_zenoh_cpp
TEST args:  --packages-above zenoh_cpp_vendor zenoh_security_tools rmw_zenoh_cpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/18840
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/28547/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/21405/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/8405/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/27402/)

**Comment by JEnoch** [comment]
https://github.com/Mergifyio backport kilted jazzy humble

**Comment by jmachowinski** [comment]
While this fixes the deadlock, I think it introduces a use after free issue. 
E.g. If the waitset is deleted after event_condition_mutex_ was released.
