### PR TITLE
SROS: add ACL rules for TRANSIENT_LOCAL pub/sub (fix #753)

### LINKED ISSUE #753: SROS: the ACL rules generated for pub/sub lack the `**/@adv/**` key expr
### Generated by Generative AI

No

### Operating System:

ALL

### ROS version or commit hash:

ALL

### RMW implementation (if applicable):

rmw_zenoh_cpp

### RMW Configuration (if applicable):

_No response_

### Client library (if applicable):

_No response_

### 'ros2 doctor --report' output

_No response_

### Steps to reproduce issue

I've not been able to reproduce yet, because of #752.
But I think such steps will show the issue:

1. follow the instructions from https://github.com/ros2/rmw_zenoh/blob/rolling/zenoh_security_tools/README.md to generate the Zenoh configuration files with rules allowing only the `chatter` topic
2. run: `ZENOH_SESSION_CONFIG_URI=talker.json5 ros2 topic pub /chatter std_msgs/msg/String "{ data: 'Hello' }" --qos-durability transient_local`
3. wait 6 seconds
4. run: `ZENOH_SESSION_CONFIG_URI=listener.json5 ros2 topic echo /chatter`

### Expected behavior

The `ros2 topic echo` command shall receive 5 messages at startup (because it is TRANSIENT_LOCAL + KEEP_LAST(5) ). 

### Actual behavior

The `ros2 topic echo` doesn't receive historical publications, but only live publications.

### Additional information

As explained in https://github.com/ros2/rmw_zenoh/issues/731#issuecomment-3200530285 the TRANSIENT_LOCAL and RELIABLE behaviors are implemented via the Zenoh AdvancedPublisher. It adds a Queryable on such a key expression:
`0/chatter/std_msgs::msg::dds_::String_/TypeHashNotSupported/@adv/pub/18bf4236bf6b467ee3ec28d43d182289/15/_`
This Queryable allows an AdvancedSubscriber to retrieve missed publications as such:
1. It performs a `"query"` on `0/chatter/std_msgs::msg::dds_::String_/TypeHashNotSupported/@adv/**` to get historical publications from all AdvancedPublishers
2. The AdvancedPublishers send `"reply"` messages on `0/chatter/std_msgs::msg::dds_::String_/TypeHashNotSupported` (same keyexpr than original publications)

The configurations generated by `generate_configs` shall allow:
* for a Publisher: 
  - in **egress**: `"put"` and `"reply"` on `"<domain_id>/<full_name>/*/*"` 
  - in **egress**: `"declare_queryable"` and `"liveliness_token"` on `"<domain_id>/<full_name>/*/*/@adv/pub/*/*/_"`
  - in **ingress**: `"query"` on `"<domain_id>/<full_name>/*/*/@adv/**"`
* for a Subscriber:
  - in **egress**: `"declare_subscriber"` on `"<domain_id>/<full_name>/*/*"`
  - in **egress**:  `"query"` and `"declare_liveliness_subscriber"` on `"<domain_id>/<full_name>/*/*/@adv/**"`
  - in **ingress**: `"put"` and `"reply"` on `"<domain_id>/<full_name>/*/*"`
  - in **ingress**: `"declare_queryable"` and `"liveliness_token"` on `"<domain_id>/<full_name>/*/*/@adv/pub/*/*/_"`

### PR DESCRIPTION
**Pull request by JEnoch**
## Description

In zenoh_security_tools `config_generator`: add missing access control rules for TRANSIENT_LOCAL Publishers and Subscribers:

* for a Publisher: 
  - in **egress**: `"put"` and `"reply"` on `"<domain_id>/<full_name>/*/*"` 
  - in **egress**: `"declare_queryable"` and `"liveliness_token"` on `"<domain_id>/<full_name>/*/*/@adv/pub/*/*/_"`
  - in **ingress**: `"query"` on `"<domain_id>/<full_name>/*/*/@adv/**"`
* for a Subscriber:
  - in **egress**: `"declare_subscriber"` on `"<domain_id>/<full_name>/*/*"`
  - in **egress**:  `"query"` and `"declare_liveliness_subscriber"` on `"<domain_id>/<full_name>/*/*/@adv/**"`
  - in **ingress**: `"put"` and `"reply"` on `"<domain_id>/<full_name>/*/*"`
  - in **ingress**: `"declare_queryable"` and `"liveliness_token"` on `"<domain_id>/<full_name>/*/*/@adv/pub/*/*/_"` 

Fixes #753

### Is this user-facing behavior change?

No.

### Did you use Generative AI?

No.

### CODE REVIEW

File: zenoh_security_tools/src/config_generator.cpp [hunk 1]
```diff
@@ -97,14 +97,46 @@ bool replace(
...
+    key_exprs_ret.push_back(std::to_string(domain_id) + "/" + name + "/*/*");
+  }
+
+  return key_exprs_ret;
+}
+
+//==============================================================================
+// Convert topic names to allowed key expression for Zenoh AdvancedPublisher's queryable and liveliness token
+json to_adv_pub_queryable_key_exprs(
+  const std::set<std::string> & key_exprs,
```
Comment (ahcorde) [inline zenoh_security_tools/src/config_generator.cpp:120]: include `<set>`

**Review by ahcorde — CHANGES_REQUESTED** [review]

**Review by ahcorde — APPROVED** [review]

**Comment by JEnoch** [comment]
Pulls: ros2/rmw_zenoh#779
Gist: https://gist.githubusercontent.com/JEnoch/32a7012b2d011c9d2270d08bfde53687/raw/0623c2bc0b7ba65fed77f5e1369645115584b61c/ros2.repos
BUILD args: "--continue-on-error" --packages-above-and-dependencies zenoh_cpp_vendor zenoh_security_tools rmw_zenoh_cpp
TEST args:  --packages-above zenoh_cpp_vendor zenoh_security_tools rmw_zenoh_cpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16916
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/24832/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/18862/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/4282/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/25346/)

**Review by Yadunund — APPROVED** [review]
This is great!

**Comment by Yadunund** [comment]
@mergifyio backport kilted jazzy humble
